//SPDX-License-Identifier: AGPL-3.0-only
pragma solidity 0.8.9;

contract SpriteStorage7 {

    mapping (uint8 => mapping (uint8 => mapping (uint8 => string))) internal sprites;

    constructor() {
        // mouth
        sprites[10][0][0] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABlJREFUKM9jYBgFwwkwMjTAmDPhgnUjx/8AiPYBmXYtD58AAAAASUVORK5CYII=";
        sprites[10][0][1] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABtJREFUKM9jYBgFQx8wMThAWYyNDTDBupEYEgDACAHDwU2FzAAAAABJRU5ErkJggg==";
        sprites[10][0][2] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABdJREFUKM9jYBgFwws4wFkNMAbjyPE9AL07AMI+M+qtAAAAAElFTkSuQmCC";
        sprites[10][0][3] = "BAMAAACnw650AAAAD1BMVEVHcEwAAADy3trli3X/ejjonJ3VAAAAAXRSTlMAQObYZgAAADVJREFUSMdjYBgFo2AUjIJRMAoGHgiiUHhVCRIyS4CBgdHYSEnJAZ8iRkFBgdFgHwWjgKYAACiSAXJUjeC8AAAAAElFTkSuQmCC";
        sprites[10][0][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAAB5JREFUKM9jYBgFQx/wMBhAWcwMB2CCjXDpupETEgDxdgH/OOs/dwAAAABJRU5ErkJggg==";
        sprites[10][0][5] = "BAMAAACnw650AAAAD1BMVEVHcEyebVV/VEH/cDgAAACmvNt2AAAAAXRSTlMAQObYZgAAADBJREFUSMdjYBgFo2AUjIJRMAqGFHBUFBImpIZFSFDR2ICAIhegIuHR8BwFo4BmAABhWAHOt6b/ZwAAAABJRU5ErkJggg==";
        sprites[10][0][6] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABpJREFUKM9jYBgFwwE4wFkNMEYzXKhm5IQDALMSAcDpWi9vAAAAAElFTkSuQmCC";
        sprites[10][0][7] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAAAAAQABAAA3FJ+zAAAAAXRSTlMAQObYZgAAAC1JREFUOMtjYBgFo2AUUAMIMDCwoAmxgEVRAA+jA7oQI6NDA7phoaGjATqEAQCN8AHyOs7oNwAAAABJRU5ErkJggg==";
        sprites[10][0][8] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABlJREFUKM9jYBgFQx+wwFlMEjAW47+RGBIAFPsBHtRtukQAAAAASUVORK5CYII=";
        sprites[10][0][9] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABJJREFUKM9jYBgFwx5IjByvAgAY2AAZz1B65QAAAABJRU5ErkJggg==";
        sprites[10][0][10] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAADbSGD/dZw1g7JiAAAAAXRSTlMAQObYZgAAADRJREFUOMtjYBgFo2AU0AiwMDAIoAkxhoY6oCsLDcXQKbUEQ4hvA4YQ/wcMIaaG0WAfeAAAAq8Ep9qtRSMAAAAASUVORK5CYII=";
        sprites[10][0][11] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAAB1JREFUOMtjYBgFo2AU0A8wMjo4oItNER0Nl+EFAC6OASzrkmtIAAAAAElFTkSuQmCC";

        // nose
        // beastie
        sprites[11][0][0] = "AgMAAAAog1vUAAAADFBMVEVHcEyaACOVtuXM5/89XRlZAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo2CwAKYP/A3oQg1MDYPSrawBxAgxOozG6kgEANWZA3FbGZmqAAAAAElFTkSuQmCC";
        sprites[11][0][1] = "AQMAAABvIyEEAAAABlBMVEVHcEyaACPNycgFAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzYYGFJjAYLBAAAnugAkTlq4GIAAAAASUVORK5CYII=";
        sprites[11][0][2] = "AgMAAAAog1vUAAAADFBMVEVHcEyaACP//wD/oACUZ9PRAAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUkA5EQzCEeAswhDgUMISYGkYDb9gDACbYAZFvmOR0AAAAAElFTkSuQmCC";
        sprites[11][0][3] = "AQMAAABvIyEEAAAABlBMVEVHcEyaACPNycgFAAAAAXRSTlMAQObYZgAAABhJREFUKM9jYBgFQwLUwVn/sbDqRgMIAgBEbQL72rNisgAAAABJRU5ErkJggg==";
        sprites[11][0][4] = "AQMAAABvIyEEAAAABlBMVEVHcEyaACPNycgFAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzUYWHZjAYLBAAAVJsBOZlPm24AAAAASUVORK5CYII=";
        sprites[11][0][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][0][6] = "AQMAAABvIyEEAAAABlBMVEVHcEyaACPNycgFAAAAAXRSTlMAQObYZgAAABtJREFUKM9jYBgFQwKkwVl1cJYNnCUxGkAQAABd+wE5yw2GlAAAAABJRU5ErkJggg==";
        sprites[11][0][7] = "AgMAAAAog1vUAAAADFBMVEVHcEyaACPM5/+VtuURpJG2AAAAAXRSTlMAQObYZgAAACJJREFUOMtjYBgFo2AUEAJcGCKiIQ2YQgfQhVjjR8NuJAIAKO0CgbUqVzQAAAAASUVORK5CYII=";
        // brown
        sprites[11][1][0] = "AgMAAAAog1vUAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURUdwTI06OpW25czn/xO3oEkAAAABdFJOUwBA5thmAAAAJklEQVQ4y2NgGAWjYLAApg/8DehCDUwNg9KtrAHECDE6jMbqSAQA1ZkDcVsZmaoAAAAASUVORK5CYII=";
        sprites[11][1][1] = "AQMAAABvIyEEAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURUdwTI06OpViC0kAAAABdFJOUwBA5thmAAAAFklEQVQoz2NgGAVDDNhgYUmMBgsEAACe6ACROWrgYgAAAABJRU5ErkJggg==";
        sprites[11][1][2] = "AgMAAAAog1vUAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURUdwTI06Ov//AP+gALqNasEAAAABdFJOUwBA5thmAAAAI0lEQVQ4y2NgGAWjYBSQDkRDMIR4CzCEOBQwhJgaRgNv2AMAJtgBkW+Y5HQAAAAASUVORK5CYII=";
        sprites[11][1][3] = "AQMAAABvIyEEAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURUdwTI06OpViC0kAAAABdFJOUwBA5thmAAAAGElEQVQoz2NgGAVDAtTBWf+xsOpGAwgCAERtAvvas2KyAAAAAElFTkSuQmCC";
        sprites[11][1][4] = "AQMAAABvIyEEAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURUdwTI06OpViC0kAAAABdFJOUwBA5thmAAAAFklEQVQoz2NgGAVDDNRhYdmMBgsEAABUmwE5mU+bbgAAAABJRU5ErkJggg==";
        sprites[11][1][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][1][6] = "AQMAAABvIyEEAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURUdwTI06OpViC0kAAAABdFJOUwBA5thmAAAAG0lEQVQoz2NgGAVDAqTBWXVwlg2cJTEaQBAAAF37ATnLDYaUAAAAAElFTkSuQmCC";
        sprites[11][1][7] = "AgMAAAAog1vUAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURUdwTI06OpW25czn/xO3oEkAAAABdFJOUwBA5thmAAAAIklEQVQ4y2NgGAWjYBQQAvwYIqIhBzCFGtCFWKNGw24kAgAuygKByhRpnwAAAABJRU5ErkJggg==";
        // elfie
        sprites[11][2][0] = "AgMAAAAog1vUAAAADFBMVEVHcExASSCVtuXM5/+7ThGlAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo2CwAKYP/A3oQg1MDYPSrawBxAgxOozG6kgEANWZA3FbGZmqAAAAAElFTkSuQmCC";
        sprites[11][2][1] = "AQMAAABvIyEEAAAABlBMVEVHcExASSD1Zd0VAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzYYGFJjAYLBAAAnugAkTlq4GIAAAAASUVORK5CYII=";
        sprites[11][2][2] = "AgMAAAAog1vUAAAADFBMVEVHcExASSD//wD/oAASdNstAAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUkA5EQzCEeAswhDgUMISYGkYDb9gDACbYAZFvmOR0AAAAAElFTkSuQmCC";
        sprites[11][2][3] = "AQMAAABvIyEEAAAABlBMVEVHcExASSD1Zd0VAAAAAXRSTlMAQObYZgAAABhJREFUKM9jYBgFQwLUwVn/sbDqRgMIAgBEbQL72rNisgAAAABJRU5ErkJggg==";
        sprites[11][2][4] = "AQMAAABvIyEEAAAABlBMVEVHcExASSD1Zd0VAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzUYWHZjAYLBAAAVJsBOZlPm24AAAAASUVORK5CYII=";
        sprites[11][2][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][2][6] = "AQMAAABvIyEEAAAABlBMVEVHcExASSD1Zd0VAAAAAXRSTlMAQObYZgAAABtJREFUKM9jYBgFQwKkwVl1cJYNnCUxGkAQAABd+wE5yw2GlAAAAABJRU5ErkJggg==";
        sprites[11][2][7] = "AgMAAAAog1vUAAAADFBMVEVHcExASSDM5/+VtuWXt5lKAAAAAXRSTlMAQObYZgAAACJJREFUOMtjYBgFo2AUEAJcGCKiIQ2YQgfQhVjjR8NuJAIAKO0CgbUqVzQAAAAASUVORK5CYII=";
        // frosty
        sprites[11][3][0] = "AgMAAAAog1vUAAAADFBMVEVHcEwOS12VtuXM5/9ihH+mAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo2CwAKYP/A3oQg1MDYPSrawBxAgxOozG6kgEANWZA3FbGZmqAAAAAElFTkSuQmCC";
        sprites[11][3][1] = "AQMAAABvIyEEAAAABlBMVEVHcEwOS12T4xLcAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzYYGFJjAYLBAAAnugAkTlq4GIAAAAASUVORK5CYII=";
        sprites[11][3][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwOS13//wD/oADLvrUuAAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUkA5EQzCEeAswhDgUMISYGkYDb9gDACbYAZFvmOR0AAAAAElFTkSuQmCC";
        sprites[11][3][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwOS12T4xLcAAAAAXRSTlMAQObYZgAAABhJREFUKM9jYBgFQwLUwVn/sbDqRgMIAgBEbQL72rNisgAAAABJRU5ErkJggg==";
        sprites[11][3][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwOS12T4xLcAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzUYWHZjAYLBAAAVJsBOZlPm24AAAAASUVORK5CYII=";
        sprites[11][3][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][3][6] = "AQMAAABvIyEEAAAABlBMVEVHcEwOS12T4xLcAAAAAXRSTlMAQObYZgAAABtJREFUKM9jYBgFQwKkwVl1cJYNnCUxGkAQAABd+wE5yw2GlAAAAABJRU5ErkJggg==";
        sprites[11][3][7] = "AgMAAAAog1vUAAAADFBMVEVHcEwOS13M5/+VtuVOffdJAAAAAXRSTlMAQObYZgAAACJJREFUOMtjYBgFo2AUEAJcGCKiIQ2YQgfQhVjjR8NuJAIAKO0CgbUqVzQAAAAASUVORK5CYII=";
        // ghost
        sprites[11][4][0] = "AgMAAAAog1vUAAAADFBMVEVHcExiYmKVtuXM5/9gwaHQAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo2CwAKYP/A3oQg1MDYPSrawBxAgxOozG6kgEANWZA3FbGZmqAAAAAElFTkSuQmCC";
        sprites[11][4][1] = "AQMAAABvIyEEAAAABlBMVEVHcExiYmIgDpJOAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzYYGFJjAYLBAAAnugAkTlq4GIAAAAASUVORK5CYII=";
        sprites[11][4][2] = "AgMAAAAog1vUAAAADFBMVEVHcExiYmL//wD/oADJ+2tYAAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUkA5EQzCEeAswhDgUMISYGkYDb9gDACbYAZFvmOR0AAAAAElFTkSuQmCC";
        sprites[11][4][3] = "AQMAAABvIyEEAAAABlBMVEVHcExiYmIgDpJOAAAAAXRSTlMAQObYZgAAABhJREFUKM9jYBgFQwLUwVn/sbDqRgMIAgBEbQL72rNisgAAAABJRU5ErkJggg==";
        sprites[11][4][4] = "AQMAAABvIyEEAAAABlBMVEVHcExiYmIgDpJOAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzUYWHZjAYLBAAAVJsBOZlPm24AAAAASUVORK5CYII=";
        sprites[11][4][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][4][6] = "AQMAAABvIyEEAAAABlBMVEVHcExiYmIgDpJOAAAAAXRSTlMAQObYZgAAABtJREFUKM9jYBgFQwKkwVl1cJYNnCUxGkAQAABd+wE5yw2GlAAAAABJRU5ErkJggg==";
        sprites[11][4][7] = "AgMAAAAog1vUAAAADFBMVEVHcExiYmLM5/+VtuVMOCk/AAAAAXRSTlMAQObYZgAAACJJREFUOMtjYBgFo2AUEAJcGCKiIQ2YQgfQhVjjR8NuJAIAKO0CgbUqVzQAAAAASUVORK5CYII=";
        // golden
        sprites[11][5][0] = "BAMAAACnw650AAAAD1BMVEVHcEzMdyiVtuXM5//N5/9LA4SfAAAAAXRSTlMAQObYZgAAAC9JREFUSMdjYBgFo2AUjIKRBpiMGRhMFAgpUoDgUUAICApSSxGjwGhojoJRMKwAAKvPASPkzVFSAAAAAElFTkSuQmCC";
        sprites[11][5][1] = "AgMAAAAog1vUAAAACVBMVEVHcEzMdyjNdyiSiS6KAAAAAXRSTlMAQObYZgAAABtJREFUOMtjYBgFo2AUkA5YA4gRYmwYDamRCABj6wEse6EwhwAAAABJRU5ErkJggg==";
        sprites[11][5][2] = "BAMAAACnw650AAAAElBMVEVHcEzMdyj//wD/oADNdyjMdihpcY0aAAAAAXRSTlMAQObYZgAAAC5JREFUSMdjYBgFo2AUjIJRMArIB4yCogKEVRk6E2GUAhMRipgURsN8FIyCoQIAuZcA8JER7AMAAAAASUVORK5CYII=";
        sprites[11][5][3] = "AgMAAAAog1vUAAAADFBMVEVHcEzMdyjNdyjMdihY5WzQAAAAAXRSTlMAQObYZgAAACFJREFUOMtjYBgFo2AUEACiIRhCoVMxhUIxNZaMBt5IBABCfAKHkTVjawAAAABJRU5ErkJggg==";
        sprites[11][5][4] = "AQMAAABvIyEEAAAABlBMVEVHcEzMdyhSVKy+AAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzUYWHZjAYLBAAAVJsBOZlPm24AAAAASUVORK5CYII=";
        sprites[11][5][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][5][6] = "AQMAAABvIyEEAAAABlBMVEVHcEzMdyhSVKy+AAAAAXRSTlMAQObYZgAAABtJREFUKM9jYBgFQwKkwVl1cJYNnCUxGkAQAABd+wE5yw2GlAAAAABJRU5ErkJggg==";
        sprites[11][5][7] = "BAMAAACnw650AAAAD1BMVEVHcEzMdyjM5/+VtuWVtuSV7JEkAAAAAXRSTlMAQObYZgAAAC5JREFUSMdjYBgFo2AUjIJRMApwASWCKhgFBQUUiFFkQNAoQUHn0RAfBaNgOAEA/EUBPshjsV4AAAAASUVORK5CYII=";
        // grey
        sprites[11][6][0] = "BAMAAACnw650AAAAElBMVEVHcExjOzOVtuXM5/9jOzLN5/8r3gPUAAAAAXRSTlMAQObYZgAAAC9JREFUSMdjYBgFo2AUjIKRBpiMGRhMFQgpUoDgUUAICApSSxGLwGhojoJRMKwAALy4ASdbm6+FAAAAAElFTkSuQmCC";
        sprites[11][6][1] = "AgMAAAAog1vUAAAACVBMVEVHcExjOzNjOjN8jGCpAAAAAXRSTlMAQObYZgAAAB5JREFUOMtjYBgFo2AUkA5YEzCFAjCEGB1GQ2okAgAH+wD8rXu4wAAAAABJRU5ErkJggg==";
        sprites[11][6][2] = "AgMAAAAog1vUAAAADFBMVEVHcExjOzP//wD/oAARS3X1AAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUkA5EQzCEeAswhDgUMISYGkYDb9gDACbYAZFvmOR0AAAAAElFTkSuQmCC";
        sprites[11][6][3] = "AgMAAAAog1vUAAAACVBMVEVHcExjOzNjOzISkGF+AAAAAXRSTlMAQObYZgAAAB9JREFUOMtjYBgFo2AUEACiIRhCoaHECIlGjAbeSAQAhCkCKxdAMoIAAAAASUVORK5CYII=";
        sprites[11][6][4] = "AQMAAABvIyEEAAAABlBMVEVHcExjOzNW2X8GAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzUYWHZjAYLBAAAVJsBOZlPm24AAAAASUVORK5CYII=";
        sprites[11][6][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][6][6] = "AgMAAAAog1vUAAAACVBMVEVHcExjOzNiOzNkVTvfAAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUEAAiIhhCoiEYQqwTMIQYHUYDbyQCAOqTAWhnVoIEAAAAAElFTkSuQmCC";
        sprites[11][6][7] = "BAMAAACnw650AAAAD1BMVEVHcExjOzPM5/+VtuVjOzLMRtX/AAAAAXRSTlMAQObYZgAAADFJREFUSMdjYBgFo2AUjIJRMApwASWCKhgFBQUUCCoSERQwIGiUoKDxaIiPglEwnAAAywMBMfdyipwAAAAASUVORK5CYII=";
        // pink
        sprites[11][7][0] = "AgMAAAAog1vUAAAADFBMVEVHcExtL1OVtuXM5/8D9BfbAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo2CwAKYP/A3oQg1MDYPSrawBxAgxOozG6kgEANWZA3FbGZmqAAAAAElFTkSuQmCC";
        sprites[11][7][1] = "AQMAAABvIyEEAAAABlBMVEVHcExtL1M/W+QBAAAAAXRSTlMAQObYZgAAABZJREFUKM9jYBgFQwzYYGFJjAYLBAAAnugAkTlq4GIAAAAASUVORK5CYII=";
        sprites[11][7][2] = "BAMAAACnw650AAAAD1BMVEVHcExtL1P//wD/oABsL1N4QhfTAAAAAXRSTlMAQObYZgAAAC5JREFUSMdjYBgFo2AUjIJRMArIByyCggKEVRkKE2GUAhMRipgURsN8FIyCoQIA9sAAvziFfb4AAAAASUVORK5CYII=";
        sprites[11][7][3] = "AgMAAAAog1vUAAAACVBMVEVHcExtL1NtL1LvXl1IAAAAAXRSTlMAQObYZgAAAB9JREFUOMtjYBgFo2AUEACiIRhCoaHECImFjAbeSAQAfkUCKB4U7c4AAAAASUVORK5CYII=";
        sprites[11][7][4] = "AgMAAAAog1vUAAAADFBMVEVHcExtL1NtL1JtLlO7ZAt+AAAAAXRSTlMAQObYZgAAAB5JREFUOMtjYBgFo2AUkA5EQzCExDCFeANGQ2okAgBycgExhb/U3QAAAABJRU5ErkJggg==";
        sprites[11][7][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][7][6] = "AgMAAAAog1vUAAAACVBMVEVHcExtL1NsL1OZmwfpAAAAAXRSTlMAQObYZgAAACNJREFUOMtjYBgFo2AUEAAiIhhCqiEYQqwBGEKMDqOBNxIBAInzAThVOEo+AAAAAElFTkSuQmCC";
        sprites[11][7][7] = "BAMAAACnw650AAAAD1BMVEVHcExtL1PM5/+VtuVtLlPtIS8IAAAAAXRSTlMAQObYZgAAADFJREFUSMdjYBgFo2AUjIJRMApwASWCKhgdBQUUCCoSFBQwIGiUoKDxaIiPglEwnAAAhPQBXjoeZAwAAAAASUVORK5CYII=";
        // quantum
        sprites[11][8][0] = "BAMAAACnw650AAAAGFBMVEVHcEyVtuXM5/8AR1sATV0ASlwATVwARlsWF545AAAAAXRSTlMAQObYZgAAADNJREFUSMdjYBgFo2AUjIKRBhiVGBiUBAgpEoDgUUAIFIcQocjVmAhFbA6joTkKRsGwAgCnegH9fpcQLwAAAABJRU5ErkJggg==";
        sprites[11][8][1] = "BAMAAACnw650AAAAD1BMVEVHcEwATV0AR1sARlsASlwj5LhMAAAAAXRSTlMAQObYZgAAAChJREFUSMdjYBgFo2AUjIJRMAooAEaORCgSUSZCEaPAaGiOglEwrAAA/9oAvEyw+RcAAAAASUVORK5CYII=";
        sprites[11][8][2] = "BAMAAACnw650AAAAFVBMVEVHcEz//wAATV0AR1sASlz/oAAARlvw8SSgAAAAAXRSTlMAQObYZgAAAC5JREFUSMdjYBgFo2AUjIJRMArIB0zJTgqEVYWYEmGUACMRihgFRsN8FIyCoQIA3qUBc6k7tTcAAAAASUVORK5CYII=";
        sprites[11][8][3] = "BAMAAACnw650AAAAG1BMVEVHcEwATV0ARlsAR1sASlwASVwARVsASFwAQ1tMd0fwAAAAAXRSTlMAQObYZgAAADRJREFUSMdjYBgFo2AUjIJRMAqwAuZAkQCCigSVHQUJKkoUMVIiqIijUFBgNNBHwSgYTgAAsEMCotP8WtsAAAAASUVORK5CYII=";
        sprites[11][8][4] = "BAMAAACnw650AAAAElBMVEVHcEwATV0ARlsAR1sASlwASFxa46jIAAAAAXRSTlMAQObYZgAAACtJREFUSMdjYBgFo2AUjIJRMArIB4zKjgKEFYkYKRA2KlBwNDhHwSgYVgAA/Q0BP2G1KNoAAAAASUVORK5CYII=";
        sprites[11][8][5] = "AgMAAAAog1vUAAAACVBMVEVHcEzMPzP/v783tYfDAAAAAXRSTlMAQObYZgAAACBJREFUOMtjYBgFo2AUEACsARhCYlOIUcXoMBp4IxEAAFPhAZbCxY3GAAAAAElFTkSuQmCC";
        sprites[11][8][6] = "BAMAAACnw650AAAAElBMVEVHcEwATV0AR1sASlwASVwARluCiJ6qAAAAAXRSTlMAQObYZgAAADBJREFUSMdjYBgFo2AUjIJRMAqwAiYHZgeCihiVDAUIGyWsSoR9jAKjYT4KRsGwAgD84wEz5plc/AAAAABJRU5ErkJggg==";
        sprites[11][8][7] = "BAMAAACnw650AAAAG1BMVEVHcEwATV0ARlvM5/+VtuUAR1sASFwBSlwASlwFi+AtAAAAAXRSTlMAQObYZgAAADFJREFUSMdjYBgFo2AUjIJRMApwAWOCKhhVCwUMCCqSCFJwIGhUoqDLaIiPglEwnAAAN88CjH/dVBUAAAAASUVORK5CYII=";

        // antlers
        sprites[12][0][0] = "AgMAAAAog1vUAAAADFBMVEVHcEz/6cyyUkflloCjQ+lsAAAAAXRSTlMAQObYZgAAAMdJREFUOMtjYGDgrGCAA90EMMWZgBCCsnWRhSpwCakiC0VQJqRbwdUAEWBaoAu1MUL1AUSIO0IVIsQZpw11v+6LrRBDuMObbkCE1JuuQtQzhT6YBxHaxh0KMZXpatU0iNC0teFQi6bGbYMw5m0NgzpGNfQ5WJLpdmgEVIg7FGIEU2go1DVAwyBM7lCYUQwMa0PBDtMNrYL7jCs0DkRtDV2A8O3WEBApGseAFAsxINIUKV4YuAtAJO8DJCEmCNXAMApGwSgYXAAAkQoxiVtMqDIAAAAASUVORK5CYII=";
        sprites[12][0][1] = "BAMAAACnw650AAAAG1BMVEVHcEyyUkf/6czlloDkloD+6cz/6Mz/6c2yUkYyOFPWAAAAAXRSTlMAQObYZgAAALlJREFUSMftkdENwjAMRGNYoGoYgLoIfkkyASPARIyOC6qS+NwfJH6Q78s5vZwuTggf0RBA4EULSr+DEkLgxQmh8SvoMEMpyhoiRggs4tQtT+bIT8ieuifLSkZoQFmsuizh345+CmuI77g5TlQqVAYxDOjUbjimfEGIzlxuDVQYlyI9uS2qjrV5WyIyGx+12PWuBBm9ld/dUFHHdd7ZQUvU47rO+40giZrrnO0giWoPG0Eul8vlcv2tXgbdEx6BZsAFAAAAAElFTkSuQmCC";
        sprites[12][0][2] = "AgMAAAAog1vUAAAADFBMVEVHcEz/6cyyUkflloCjQ+lsAAAAAXRSTlMAQObYZgAAAFhJREFUOMtjYBgFBIAWhFqBJLS9AUQy3UOIMF1dAKK4whsQQqE7QJReKJJQeByI2noVIcSwMgREimYhGa8bAyJNK5CEuAtAJO8DJCEmCNUwGkOjYBQMMgAAr9EOsX25kDgAAAAASUVORK5CYII=";
        sprites[12][0][3] = "AgMAAAAog1vUAAAADFBMVEVHcEz/6czlloCyUkeGojTrAAAAAXRSTlMAQObYZgAAAPZJREFUOMvt0LFNxDAUBuBfeZVPirsbwQ39FYYTU5xDJF/hASyREbKEj4LmSiQoPACFl4ANTIFYgI44sZOMQJG/yIs/y3/xgCE3/e4K7K7VC0qcES0gWtYUqVTrhoNrhOozsccnHftKx89fk0n4LysNs/KZt4XCra8N6/gbLcRDIvIzHQKBdbVBoHMhn/pSDy8kO+AS6ALUttAZ1Svw3eNQqNbg78C9R+wy8SbcBYB+yPlMpPwxzSNXoZDLFbIphA89zfgwLydOt+T0TFKNtVzZmfJ/vsHqRVzah8MpffdL1fBkXIqwK+LjgplfEU1jVbVly5Z/kT/o2kRTV3Ri3gAAAABJRU5ErkJggg==";
        sprites[12][0][4] = "AgMAAAAog1vUAAAADFBMVEVHcEyyUkf/6czlloBjmmhIAAAAAXRSTlMAQObYZgAAAOFJREFUOMtjYMACRDC5sqhCJUDM7oAswngBSLChCk3ALiTnwIoQCWDcAiSlHdgDYCKsFxifAKlKBsavMKF4B4ZcIAXE2VDjGF+CVDCAVMpdgAixbwGZAxYCMUEAJAUUYsiEqGRggHMZqh3A5jEwQMx5C6SlroDZDBCbxJeAXL82BKwDrF+0CuR6xldrA6QgQktYq1aDWeGrtlaBXcG+Nm7VVYgD41atArtCbtWqrVBHs8atWguiq1ZtRfj21QoQpbU6ABEmcWtApNVWpIBj3wAi+S4ghyWEcmAYBaNgFAwuAAAc+DXQMNjV8gAAAABJRU5ErkJggg==";
        sprites[12][0][5] = "CAMAAABiM0N1AAAATlBMVEVHcExMbf//zr8nS++yUkflloDloJImS+8USMz/6cz/6c0USM3+6cwmS+7/zr6yU0cmSu8VSMzlloGzUkfll4D+zr/kloBMbP8USczloZKRJ1PBAAAAAXRSTlMAQObYZgAAASJJREFUWMPtlduOAjEIhpWhQD3uSXf3/V90KagX2mk72Zh4wRcTL/j9YEDjavUEgEQh+G9SiIj5jUV6HhFWfomqSfnhdYG7puLxaC2p1bUD0DaJAFyiFRMBs9f1jdoiAuBv66ifoXuRrofBXqzP3lg4yDV7sOx9m+1UFsinYmKheRHZpss0+6myT5GJ93xBWksSv5lRO/FW+KBdJn+09o7INTqVvM98j8S+aNQ+/y0225Awpa+EI7+CYzpjqx+qasiE3RgOiQZSx82uKxqZG1PO2NXk/kCfKmqGikZ79acusYRzQdfkoXPkXVF9VF2uGfJcs7m2hiUeS29c9VjLpZQGRXZcG+mx5Asc/xdAu3CtkhZ5zLW4EARBEARBEARBELwkfw7KCs5PCbbkAAAAAElFTkSuQmCC";
        sprites[12][0][6] = "CAMAAABiM0N1AAACalBMVEVHcEz+6czll4CyU0floJL/zr//6Mz/6cyyUkflloB2TUddXQo/QD0whDF2QipwLW9UK19hNJkZWA1UNEsnZzcUXyxdLjk5Zw1IXRGJSWcROWRLNj9jWGMzX19ANE1wMlEAbV1ySDvkoJKGFWkeUJdhRm1qFliEAK1dRxZiYDeVHyVjQj4ZXilUVwNlHzZnKSiPD2ANiDcZK1BLLVFXZnWGNDAndC9cFjIoVQklZWc0ZCR3aws3ZwCKPyBwMVA7YXEqZVx9PypfUiNlSABRKWE5ZAROR019Iy9rSVQYhBgQcylmMABEbJZJV2FUaFJGTBU8ZyxKjjpfXjtYZRZuC7A9chp1TT9qQUM2UC8/RElLcIxiJHEuWn5ULkoxLDkfZ1lSZFl/ZClVUHM+an8+Ph0vS15NZwBmaVsWULsyczJuPZGZP2B+MCtpURxZVDkabn0sbUV8OUtpT3eUNDSkKSi1ogBgS0ewHV81QCkjZl5URl1xcUC4TD4AaRIzVzAuhhklZ1Mwbi4yT4JqX0NeVFeINzpBZweVPBUucmQ6UjE7Tlg7R1eMCJ5gMoBkXjxGOlxfZWyZT5A9aE17fm4+hDn+zr9wTFAiYXYOfVVXPaE9PUIhh0eAS0xIcahjTApqbil8XUd4MkRhr2U1eVRMcKxeiVh2IH9Lc4CfiU1gN119MEspdT57GGgugHk/TE2ZMH98bFRNj1ZpchhdTcNNkJRranB7jGGHaZdeqioyUVqCZ4awTE5SK25UO5NDgQBPQXOKZKIXaE93Z3aPTJ2FY4Z9cjtATXxHgndJgstLRklRLIF5jXp6aIM/VljX7hnrAAAAAXRSTlMAQObYZgAAAddJREFUWMNjYKABYGXZt3PldBZWYlR2zqrzx6UyiIWFZdWmZTMi9AmZ4xnfPfvgAqByRWyy3rVrtm5YcXrpsUYPFfzmuMb2zNl25vjcmmAjZUxZr7iuiRvXH1iyeworq7UcPnNsElhZj5w4unb7otIAQ3l0WRbW7HzWqYeWH57cz8rKoorPoHAWVtbVm7fs2MXKWh3KyoJuEEt0YS7rtLOsva1NLCwGeAKcNYWFZd6e/awnT7GW+9myoBskrWMSlZXXN4mVtaEk3UGdBbdBLGaJBR2LWVnXLawMtNKU5UOT5pHQNo4pKq5va6lKdtIQF8ZtkKiCaUbmhJl755eFWWpJCnKjywtI6bKy+vpEVqTZs7AI4QsjMSWWpJzm9tQQVlYZfi4sCkSACUPPwsVZjYUFf/SzsJg7urnbAZXz4lLBwQkEHMTkAqBKDnz2cYCMYibSIEpVEKmKg52RoEFgdxN0EDs7B0Fj2IlwEBM7O15FIGOAdhF2NUgZJwcuhRBj2IiJWA52EODEbhbYGIJ+R1HLji0YSDEHySR2TDmgICM7J5EGgSMXFBCcmFKcbOzEmwM2ChTD2GQ4STIHbBbJEqNgFIyCUTAKRsEoGAWjYBSMglEwCgYlAACKdFh8CFUWhgAAAABJRU5ErkJggg==";
        sprites[12][0][7] = "CAMAAABiM0N1AAAAUVBMVEVHcEz/Ukz/zr//6c2yUkflloDloJLvLSbMFCD/6czNFCCyU0f/6MzkloCzUkeyUkb+6cz+zr/ll4DlloHuLSb/z7//zr7loJPMFCH+Ukz/Uk0lYiMkAAAAAXRSTlMAQObYZgAAASNJREFUWMPtlN1uwjAMRlvjOHYZsD8G2/s/6Oykm9Q1TYIQF5N8hMSFP44dp3QYHgAQKwT3JpmIosLc8vDVchovJieOo9E2Mcc4flm0lNTq+JlMADzVPQBjpmAiiDHX9YuqI+luIA3/Yb+hvyJbD6RPpAtXFg68yFLh3MbLOe2btkWUkgA5vzrbj2iucm1Fy2hh2XOXd2rtiLJE88WO9hzZczYR1a8/x5i2GxKGw2vAnn8BhoC1fojhrctkonsTnSkU2Tc16mkPJIJNjXQMFOS5GjpaK0FsH15jAbeCe63v5KnrOlS0s9FLrtSmefZFVkprmGvHvhfur0nWtdwBO1/ddrm2iLAuHW7xJJXdcKkSbvIYp80mg+M4juM4juM4jvOf+AZdqgrggXCBZQAAAABJRU5ErkJggg==";
        sprites[12][0][8] = "BAMAAACnw650AAAAJ1BMVEVHcEyyUkf/6czlloCyUkb/6Mz/6c3+6cyyU0ezUkfkloDlloHll4ASHj4DAAAAAXRSTlMAQObYZgAAAThJREFUSMftkkFOAzEMRWNYsYuTIrFkHChiR1IJsYQjwFGQOABX4QZcgZPx7XRmMqXTA6B4UcX5b2z3O845Ry/ercQkUZBhDYJUqXibeQ26ipKtUMmr3aDGpCrJCQbyu8oVXYeK9ovT1JuGpmnMoFC40bvnMd2HfUr61aWewuDYkeo0N6Zik3hIYagzsdcc/AxZoYyu9GUziULhAHrVn3uF5NsseGIPH/iwEnRPHM0h+knsg/ZsHKMtdCoDcamDwvkNzAfUDP4ICArv14J/IgKZfWz2HDKgi6pUT0QkM3NpfUq4gHCXpyUaVaSFJIHZyrx8iqiLaNvZRcqLTe3srnEc6cfuc7l7RrG3uV+0Mn/eIhwRuR6zMzB87AmBehjP52COv6+Y5nNrx7Jjm5x8rj169OjRo8c/jF/x8iKjHOEE8gAAAABJRU5ErkJggg==";
        sprites[12][0][9] = "BAMAAACnw650AAAAJ1BMVEVHcEzlloCyUkf/6cyyU0eyUkblloH/6Mz/6c2zUkf+6czll4DkloAH07H4AAAAAXRSTlMAQObYZgAAARpJREFUSMftkkFOAzEMRY17ARwv2DqpEGJHmmU3hROg3qBn4SgchYvx42REp03ZV8qXRpPx/3lxJiG6Y3FKt6z0aj0TS76RSlqC9YzmceqomlsqZoSKHAZtnMoTzICRFhX14aUwPQseIwbwGH14CapTE5oxikWQlAEKM5sVEAqUKMoVivVb3EJgq8ZiA5SDqpV3tM0WT+EahY6klgPrjl4QigNUBwUPIZAAxfvrHNVAMJ4RxHIHZv9eodrWQDAnlbpN2LWrzzWohojrL8jeHq1RDeRGRJU1JxE/RClvS2jjIEyUj596LDjpFgLqcQk9lF4S3df94DZJW+Zd/hrvpYizdyQWbnvn8//US4vJyf672kZTU1NTU1P3rl/foinjSIeU0QAAAABJRU5ErkJggg==";

        // antler_accessory
        sprites[13][0][0] = "AQMAAABvIyEEAAAABlBMVEVHcEz///+flKJDAAAAAnRSTlMAslP8H5gAAAB1SURBVCjPY2BgEDj8waGBAQQUbdYo1B8AMpgPiX6yPwAWs1Oa/RDMYFD+NlUQwnLSfDIRyvK0//8frOP/fxWoGJPmk0cQFqNatBSUZRWoDmExnHx3CGIbg5uLC1RM+4cFlCXgIgBlKTjxQFkODEwMo2AUEAMA5+0c5i0rOXoAAAAASUVORK5CYII=";
        sprites[13][0][1] = "BAMAAACnw650AAAAFVBMVEVHcExsothSerJtothSerNSe7JTerKtY3JlAAAAAXRSTlMAQObYZgAAAIlJREFUSMftkSsCwCAMQ6FimsIFSm8wMb/7n2ofRcM+qM30OSCEJoTwDVUGRMwDKtb1XaQjTpVTs6JLDbG2ToS2pwWp2YudSPurnPGl41xgwIxWXSxSrmhVMUvZRUlhKPQusre2rDY9WsdEOdhyo150LdGU28c9mHg2onzzTc8NPG47juM4jvMfGylKCAoK5CEIAAAAAElFTkSuQmCC";
        sprites[13][0][2] = "BAMAAACnw650AAAAD1BMVEVHcEz/SVPYLUz/SVLZLUxZr+cmAAAAAXRSTlMAQObYZgAAAEVJREFUSMdjYBgFo4A2QIAINYxE6GA0QOUKYFPGJIgqKqiAzSgVBkEkJQJKWO1jQuUqYHe5Ah4to2AUjIJRMApGwSgAAQBwvgGEKPc/EQAAAABJRU5ErkJggg==";
        sprites[13][0][3] = "BAMAAACnw650AAAAFVBMVEVHcEwAAAD//wD/AAD/AP8AAP8A/wBunqE8AAAAAXRSTlMAQObYZgAAAMlJREFUSMftkcENgzAMRW2gPbtVB0CZoFUWyIEBeskAvbD/CMVxQpVgFQ49VX6giKDn+GMACrQuALguDb+TkC+3VlApqOi41I2yCYtyVyQ3LlIn0jAB9V6JlCTpgSI1oealVWonaSm3I3Af5zy/+ISeny/pzt9yLRnlJMZz1CHIq9MzBd3EEmnKUgR1TqkdZAmiNqd2eNrAWZIcO1I8IGGsdqpSpUJN6x/USkjqjGgnkYcD0iYq6VqdAW8B9ik/8TuHJMMwDMP4G96tDw0qNHg8cgAAAABJRU5ErkJggg==";
        sprites[13][0][4] = "CAMAAABiM0N1AAABzlBMVEVHcEx5n97Z//+i//9p//9+/P+E1dp4//8A///I//9nkOyJ//946P+I//9Nwv9r1v85/9HHzP9G//9SyP+r3v8/rajo3f+Gi/KS7/LdR/+03P+X5/W8bf+k/+iy+uf5zP9p+92K/9PT/eXC1f+j//+Q//+L//9s//82//+0ZuRY6MKH/+G7gP9y/93U5v8A9qmd///s2+g7kP9Rpv/T/f5Q//9++/C76P+ls/+///9L///UaIuuYdp5//dr//2m//9f//+P+v+8/9RJvP+h//81v/935/LDyKa59vwk//kp//8xyf8L/8KKj/RV9P9tifZ9qv/b2P9kvP815v8X//+rbv+n3v//9/8YjekA3v+Ho/871v9t0LBj1+8rt/+xqNWL/9fp7OR6/8HLsv/B///E//+V//8+//8w//9Xd+Jqof+10/9G7f9Q2eqk//gg/6qSr9dGZf+mwOYu//nH/+7//+PB2phd//8A/9io/82e/81A/81jyf9xqPig9v8P1vMHz42ThcxEg4Na9sOzxvxY6/+wtv9g6v+jGpVs/4Oj6P9Tmf9h/92M//81/////4r/yf84/82p/P+w+f98/85VyYW0zaJ+dP+7//ap7/9LRH3MAAAAAXRSTlMAQObYZgAAAQtJREFUWMNjYBgFZAApIyhDgBFVglsYyhDnJcYcSW23YDBDQ1qEGVmCS1RWCcxgN5bgI8IgHdfQ9Awg7aOmySGILCGkIG9gAqSTwpz0OIgwyCUkK7WlgyEu0ENdRQZZQk7R0My/hqGqPjbCTpcYv2WmTWub0D0pJcBTFVVC3zSoKbuInbMgIZyowGbp6mydMnlGX7w5uox3TnFtdT5neYU9cdEW2T6zZ2pvojWmjFdpLntjXZ4zsQkgamL/9GRLbDJ+zZUNJY7EJ6Volhgb7DK+ZYUOpCRKdwtl7BJatlakJW9+JuziPGKkZhRW7MJso0XIKBgFo2AUjIJRMApGwSgYBaNgFIyCUTDyAACUFi4pXJxRRgAAAABJRU5ErkJggg==";
        sprites[13][0][5] = "BAMAAACnw650AAAALVBMVEVHcEzqZVblTknRPj6t04GAsmVgk1H/0czz/+WyUkflT0mt04CAsmTqZFbQPj40bs/iAAAAAXRSTlMAQObYZgAAAJpJREFUSMdjYBhEgHMCusgEbKoMGJRQ+NiMYlJmVjZAcFkzU7EoUiwUEjJC4qe6BGCoYRYvF5QyVkAIsHS4YdomXigoiFAUxuDS0YpFkaCgrDHcUWkhLjuwKBIEArsFSIq2+GC6CahGCMm6VBcXNyy+ExQURviOFWhUAJZwQjYIaFRaKLbQVFZSYhgFo2AUjIJRMApGwSggDQAALCcVS9N/5hQAAAAASUVORK5CYII=";
        sprites[13][0][6] = "BAMAAACnw650AAAAIVBMVEVHcEyypqbY1tD///+yp6azpqbY19CypqfZ1tDY1tH///6Z9Y1vAAAAAXRSTlMAQObYZgAAAM5JREFUSMftkUGOwjAMReOi2ee7QmzrH4l9zY5dr8INOMLMDUZcGKdFUBCa/Yg8VU1rPztuk9Jn0tmy5nUQW8Rd7u/czWl5SPEoBuSkwy2ysSWNRxvp4wLOU/FbxLPguVGCe2ejlpGXLNXrbZ5GbD3QWJwFPOovCrOoLwNxWEvWO2nkN9SJg9virBslgRaSGsMDpjyg7qV8+v4EhPMTWiyYlNXmi5O+EOnIhLXniTOWX3+woGq13urmteLNMcQEc+n052EBqdFoNBqNxv/jCpYMFcek8ntSAAAAAElFTkSuQmCC";
    }

    function getSprite(uint8 partId, uint8 typeId, uint8 spriteId) external view returns (string memory) {
        return sprites[partId][typeId][spriteId];
    }

}