//SPDX-License-Identifier: AGPL-3.0-only
pragma solidity 0.8.9;

contract SpriteStorage1 {

    mapping (uint8 => mapping (uint8 => mapping (uint8 => string))) internal sprites;

    constructor() {
        // brows
        // beastie
        sprites[3][0][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][0][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][0][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwWAAOaACPgAC/pzSVeAAAAAXRSTlMAQObYZgAAADlJREFUOMtjYBgFo4BoEApGyEA01IExNARFKMr+APOfpcgijA3MDAwHmByQhJggVAN+oVEwCoYkAACADAeG4FdbpgAAAABJRU5ErkJggg==";
        sprites[3][0][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][0][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][0][5] = "AgMAAAAog1vUAAAADFBMVEVHcEwWAAOaACPgAC/pzSVeAAAAAXRSTlMAQObYZgAAADhJREFUOMtjYBgFo4BYEBrCwCAaiizCGArkhoY6IAttsGRgyOFDFmICQoYGICQEDjCPBvIoGAYAAE6DBhT8k/2hAAAAAElFTkSuQmCC";
        sprites[3][0][6] = "AgMAAAAog1vUAAAADFBMVEVHcEzgAC8WAAOaACOdrBaWAAAAAXRSTlMAQObYZgAAAERJREFUOMtjYBgFowAr4FoAwUhA/xcDw/ofKEJTwxuYroYhizAFiDIwhLA2IAkxMgCFHIAQGTA6MGLYiU1oNCZGwZADAMRwCVeeYbM5AAAAAElFTkSuQmCC";
        // brown
        sprites[3][1][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][1][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][1][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAAByLS2yUkeAui0zAAAAAXRSTlMAQObYZgAAADlJREFUOMtjYBgFo4BoEApGyEA01IExNARFKMr+APOfpcgijA3MDAwHmByQhJggVAN+oVEwCoYkAACADAeG4FdbpgAAAABJRU5ErkJggg==";
        sprites[3][1][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][1][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][1][5] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAAByLS2yUkeAui0zAAAAAXRSTlMAQObYZgAAADhJREFUOMtjYBgFo4BYEBrCwCAaiizCGArkhoY6IAttsGRgyOFDFmICQoYGICQEDjCPBvIoGAYAAE6DBhT8k/2hAAAAAElFTkSuQmCC";
        sprites[3][1][6] = "AgMAAAAog1vUAAAADFBMVEVHcEyyUkcAAAByLS3JCzHHAAAAAXRSTlMAQObYZgAAAERJREFUOMtjYBgFowAr4FoAwUhA/xcDw/ofKEJTwxuYroYhizAFiDIwhLA2IAkxMgCFHIAQGTA6MGLYiU1oNCZGwZADAMRwCVeeYbM5AAAAAElFTkSuQmCC";
        // elfie
        sprites[3][2][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][2][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][2][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwABQBASSB1dzyk9HQ3AAAAAXRSTlMAQObYZgAAADlJREFUOMtjYBgFo4BoEApGyEA01IExNARFKMr+APOfpcgijA3MDAwHmByQhJggVAN+oVEwCoYkAACADAeG4FdbpgAAAABJRU5ErkJggg==";
        sprites[3][2][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][2][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][2][5] = "AgMAAAAog1vUAAAADFBMVEVHcEwABQBASSB1dzyk9HQ3AAAAAXRSTlMAQObYZgAAADhJREFUOMtjYBgFo4BYEBrCwCAaiizCGArkhoY6IAttsGRgyOFDFmICQoYGICQEDjCPBvIoGAYAAE6DBhT8k/2hAAAAAElFTkSuQmCC";
        sprites[3][2][6] = "AgMAAAAog1vUAAAADFBMVEVHcEx1dzwABQBASSDae9s1AAAAAXRSTlMAQObYZgAAAERJREFUOMtjYBgFowAr4FoAwUhA/xcDw/ofKEJTwxuYroYhizAFiDIwhLA2IAkxMgCFHIAQGTA6MGLYiU1oNCZGwZADAMRwCVeeYbM5AAAAAElFTkSuQmCC";
        // frosty
        sprites[3][3][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][3][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][3][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwABxQOS11XeYGzHfubAAAAAXRSTlMAQObYZgAAADlJREFUOMtjYBgFo4BoEApGyEA01IExNARFKMr+APOfpcgijA3MDAwHmByQhJggVAN+oVEwCoYkAACADAeG4FdbpgAAAABJRU5ErkJggg==";
        sprites[3][3][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][3][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][3][5] = "AgMAAAAog1vUAAAADFBMVEVHcEwABxQOS11XeYGzHfubAAAAAXRSTlMAQObYZgAAADhJREFUOMtjYBgFo4BYEBrCwCAaiizCGArkhoY6IAttsGRgyOFDFmICQoYGICQEDjCPBvIoGAYAAE6DBhT8k/2hAAAAAElFTkSuQmCC";
        sprites[3][3][6] = "AgMAAAAog1vUAAAADFBMVEVHcExXeYEABxQOS13haREjAAAAAXRSTlMAQObYZgAAAERJREFUOMtjYBgFowAr4FoAwUhA/xcDw/ofKEJTwxuYroYhizAFiDIwhLA2IAkxMgCFHIAQGTA6MGLYiU1oNCZGwZADAMRwCVeeYbM5AAAAAElFTkSuQmCC";
        // ghost
        sprites[3][4][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][4][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][4][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAABiYmKWlpb7vrZvAAAAAXRSTlMAQObYZgAAADlJREFUOMtjYBgFo4BoEApGyEA01IExNARFKMr+APOfpcgijA3MDAwHmByQhJggVAN+oVEwCoYkAACADAeG4FdbpgAAAABJRU5ErkJggg==";
        sprites[3][4][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][4][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][4][5] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAABiYmKWlpb7vrZvAAAAAXRSTlMAQObYZgAAADhJREFUOMtjYBgFo4BYEBrCwCAaiizCGArkhoY6IAttsGRgyOFDFmICQoYGICQEDjCPBvIoGAYAAE6DBhT8k/2hAAAAAElFTkSuQmCC";
        sprites[3][4][6] = "AgMAAAAog1vUAAAADFBMVEVHcEyWlpYAAABiYmJo6g/vAAAAAXRSTlMAQObYZgAAAERJREFUOMtjYBgFowAr4FoAwUhA/xcDw/ofKEJTwxuYroYhizAFiDIwhLA2IAkxMgCFHIAQGTA6MGLYiU1oNCZGwZADAMRwCVeeYbM5AAAAAElFTkSuQmCC";
        // golden
        sprites[3][5][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][5][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][5][2] = "BAMAAACnw650AAAAD1BMVEVHcEwAAADMdyjlpFABAADeecEjAAAAAXRSTlMAQObYZgAAAEhJREFUSMdjYBgFo2AUjALygKAjmBTEo4RRUFBQAE7hMkeJ2diAgQFIKOE0i1EBqADEACpkwmUUEzJHgRJFo2AUjIJRMAqoAAC8wwLZ+fWWaQAAAABJRU5ErkJggg==";
        sprites[3][5][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][5][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][5][5] = "BAMAAACnw650AAAAElBMVEVHcEwAAADMdyjlpFABAAAAAAFJdT50AAAAAXRSTlMAQObYZgAAAEtJREFUSMdjYBgFo2AUjAJygGCgoACIZhQUEcSlhlEQCMCKgUAAlyJlBmZFEEPIgMEIlyImKGZQgGLKgAEDA/NoFI6CUTAKRgGNAQBZIAKX50e9fAAAAABJRU5ErkJggg==";
        sprites[3][5][6] = "BAMAAACnw650AAAAFVBMVEVHcEzlpFAAAADMdyjlpFEAAQAAAAEgfnLHAAAAAXRSTlMAQObYZgAAAFhJREFUSMdjYBgFo2AUjAJ0oBQEpZVwq2EyNgbLqhkbK+BUpCgoKAyUZTIUdBTCaZAgA6MgiCEowCCIyygWBqgiASjGBRiBkowEPUisolEwCkbBKBgFFAAATi4D3DprU9sAAAAASUVORK5CYII=";
        // grey
        sprites[3][6][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][6][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][6][2] = "AgMAAAAog1vUAAAADFBMVEVHcEwAAABjOzOdZ1Lrq5kDAAAAAXRSTlMAQObYZgAAADlJREFUOMtjYBgFo4BoEApGyEA01IExNARFKMr+APOfpcgijA3MDAwHmByQhJggVAN+oVEwCoYkAACADAeG4FdbpgAAAABJRU5ErkJggg==";
        sprites[3][6][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][6][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][6][5] = "BAMAAACnw650AAAAD1BMVEVHcEwAAABjOzOdZ1IBAAAdQkakAAAAAXRSTlMAQObYZgAAAEpJREFUSMdjYBgFo2AUjAJygKOgoACIZhQUFMSlBiQHlgTRDrgUKTMwK4IYQgYMRgI4FDFBMYMCFFMGDBgYmEejcBSMglEwCmgMAAMfArTAOCdKAAAAAElFTkSuQmCC";
        sprites[3][6][6] = "BAMAAACnw650AAAAElBMVEVHcEydZ1IAAABjOzOcZ1IBAAAl/68yAAAAAXRSTlMAQObYZgAAAFhJREFUSMftzNEJgDAMBNCkE+R0AQ04gGQC91/KtvpVCBX8vUdCAjkiQkQ0OvyZ7nmmRPSrR2xpaAfWei0nsKSPIHq1BSbIXmkttMXezqj18MTXEBER/XADAz0DqABxHaUAAAAASUVORK5CYII=";
        // pink
        sprites[3][7][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][7][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][7][2] = "BAMAAACnw650AAAAGFBMVEVHcEwAAACrS3ltL1MAAAEAAQABAABsL1NULichAAAAAXRSTlMAQObYZgAAAEtJREFUSMdjYBgFo2AUjALygKAggsQBGAVFBAWAVGAiiMJljjmTkgIDA5AwxmkWiwFQAYgBVMiMyyhmZI4BJYpGwSgYBaNgFFABAAAh4wNDi+4LQQAAAABJRU5ErkJggg==";
        sprites[3][7][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][7][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][7][5] = "BAMAAACnw650AAAAFVBMVEVHcEwAAABtL1OrS3kAAQABAAAAAAH6JA9GAAAAAXRSTlMAQObYZgAAAE1JREFUSMdjYBgFo2AUjAJygIigmACIZgwUFMSlhlFQUFAExADSggK4FCkzMCuCGEIGDEa4FDFBMYMCFFMGDBgYmEejcBSMglEwCmgMAIgMAp+ZA69cAAAAAElFTkSuQmCC";
        sprites[3][7][6] = "BAMAAACnw650AAAAElBMVEVHcEyrS3kAAABtL1OrS3irSnnmYGP/AAAAAXRSTlMAQObYZgAAAFRJREFUSMftzEEKgFAIBFD9dACnaF/eILz/3fpJmyIpaDsPRGEGRYiI7tyv+0mLyNQjlrK0AlNP2waM5aNZFMcBE1SvVGTIkp1TUcvyi68lIiL6YQf/cAN8euY/WgAAAABJRU5ErkJggg==";
        // quantum
        sprites[3][8][0] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAAFhbDkFAAAAAXRSTlMAQObYZgAAACZJREFUOMtjYBgFo4ACwJrgwMgagCIUGgrBCMAIoRxGg2sUjAwAAMZ3ApE/l3cJAAAAAElFTkSuQmCC";
        sprites[3][8][1] = "AgMAAAAog1vUAAAACVBMVEVHcEwAAAAAAQAPcDjSAAAAAXRSTlMAQObYZgAAACpJREFUOMtjYBgFo4BYwBjCwCDqgCIkGsbAEBqCIhQ6FYhDR0NrFIxcAAAuJgNTmCrnwwAAAABJRU5ErkJggg==";
        sprites[3][8][2] = "CAMAAABiM0N1AAAAPFBMVEVHcEwAVF4AT10AU14AXX8AUl0AUV0AAAAATV0Ab4EARVsAUF0AaIABZ4AAAQAAYX8AWX4AAAEAV34AUn6pXJW2AAAAAXRSTlMAQObYZgAAAF1JREFUWMPt0jkOgDAMRFEDgUnYl/vfFaQI0UBhREHxX+PYlqeKGQAAwNd0uHv7U65radH4KkvqoqUhrLnt55Astv4kVblu52DKJXqTyqdF7QwqnhYNfxAAAAB/swOmkAGZTrY6zAAAAABJRU5ErkJggg==";
        sprites[3][8][3] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFpIAHDOwQBqMNg00DhMnP8AEqy9x4AMpibGwYDawBAADsBAUmBpOwUQAAAABJRU5ErkJggg==";
        sprites[3][8][4] = "AQMAAABvIyEEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAACpJREFUKM9jYBgFhIEMgwWUVc/wD8r63/gfwmDkb/zQAGEyMxwYDawBBQAlDgcVuqC7IgAAAABJRU5ErkJggg==";
        sprites[3][8][5] = "BAMAAACnw650AAAAMFBMVEVHcEwAAAAASlwAb4EAAAEAZIAAaIAAU10ARlsATV0AQ1sATF0APFoAdIIAAQAAa4EaiKNnAAAAAXRSTlMAQObYZgAAAFBJREFUSMdjYBgFo2AUjAJygKCgoACIZhF0FMSlhhGoCCwpKAdVjU3RXgZmRRBDyoDhJy5FTEDMA2I0AHEBxY4PYGBgG43CUTAKRsEooDEAAGRmBNpW1mr6AAAAAElFTkSuQmCC";
        sprites[3][8][6] = "CAMAAABiM0N1AAAAV1BMVEVHcEwAc4IAa4EAWX4AZ4AAaoEATV0AAAAAb4EAZIAAXX8AYX8ASlwAbYEAXH4AVX4AU34AaIAAUF0Aa4AAdIIAboEBAAAAU10AS1wARFsAdYIAQFsAZYCVTNPhAAAAAXRSTlMAQObYZgAAAHhJREFUWMPt0ckOgzAMRVECSZyEoQU6QNv//04iBnVXEcrynoWtWPJbOFkGAAAwk+jXe3eO7Wz1XRV5DmN1IOlRq7vpnV1X5a1f7lPWyUlibrE6HbZBEVyseZ6apOfqi+s2KNeuDl780izd/P13fmntWUEAAADA6SZAFwKRmcr8HgAAAABJRU5ErkJggg==";
    }

    function getSprite(uint8 partId, uint8 typeId, uint8 spriteId) external view returns (string memory) {
        return sprites[partId][typeId][spriteId];
    }

}